# Site settings
title: An Adventure Through Time and Space
email: elpepke41@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Emily if you couldn't tell by the name of the website.
  I'm a junior at the University of Pittsburgh with a major in Computer Science.
  I'm involved in the Women Computer Science Club, as well as the Pitt Computer Science Club (Events Chairperson).
  I like playing video games, watching movies, hanging out with friends, of course coding ;), and going on adventures.
  The site needs a lot of work, but its getting there. Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emilypepke.com" # the base hostname & protocol for your site
twitter_username: emilyofsuburbia
github_username:  pepke41

# Build settings
markdown: kramdown
